config:
  azure:environment: public
  azure:location: WestEurope
  layers:environment:
    service: shared
    names:
      - at
      - test
      - test2
      - demo
    sqlServer:
      hasFailover: true
    appServicePlan:
      - name: be
        size: s1
      - name: fe
        size: s1
  layers:global:
    program: cg
  layers:management:
    service: mgmt
    name: dev
