config:
  azure:environment: public
  azure:location: WestEurope
  metadata:program: cg
  metadata:service: shared
  metadata:environments: [at, test, test2, demo]
  environment:appserviceplan:
    - name: be
      size: s1
    - name: fe
      size: s1
  environment:sqlServer:
    - hasFailover: true
